### PR TITLE
new livery D-ELFP

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
new livery D-ELFP

Based on:

Screenshots:

fg-0

fg-2

fg-6

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
ready to be tested and merged :smile:

**Comment by HHS81** [comment]
@gilbertohasnofb and merged! Thanks a lot! :smiley:

**Comment by gilbertohasnofb** [comment]
Thanks for the merge! :smile: 

> There are pretty few interesting liveries for the C182 S out there unfortunately....
> 
> I have a list of interesting Cessna 182 S liveries if you want?

Absolutely! For the next livery, I was considering doing the D-ELGD, which is a 182S as far as I know:

https://www.planespotters.net/photo/653169/d-elgd-lgm-luftfahrtgesellschaft-cessna-182s-skylane

But please send me the list, I'd love to take a look at it!

> (I'm thinking since a while that it should be quite easy to add a Cessna 182 T [...] But first get this bird ready as possible)

Agreed (but I also can't wait for the model T, that's such a nice aircraft!)

**Comment by HHS81** [comment]
> Absolutely! For the next livery, I was considering doing the D-ELGD, which is a 182S as far as I know:

Unfortunately not.
Someone spreaded this, but actually it is a Cessna 182 T. Airliners.net already corrected the description, flugzeugbilder.de refused my correction. 

You can spot  the difference due to following:
C182 **S**:

- prolonged oil cooler intake (nose)

C182 **T**
- recessed oil cooler intake (nose)
- aerodynamic fairing in front of the nose gear
- strake on tail stab
- different wheel fairings

But go on, I will apply the uVMap to the livery of a maybe upcoming T-variant then later! :smiley:

**Comment by gilbertohasnofb** [comment]
Okay, so if I have time in the next days I might do the D-ELGD. But if you have some model S to recommend me, I'd be happy with that!

**Comment by HHS81** [comment]
I have just created a list #76  of interesting liveries, but I really don't mind other liveries as well!

**Pull request merged**
