### PR TITLE
Issue #68

### PR DESCRIPTION
**Pull request by HHS81**
Issue #68 Make use of procedural lights

-  added procedural lights
-  use of correct directional angle
-  made procedural lights selectable dependant on renderer (ALS) and user choice via Aircraft-Menu
-  changed electrical.nas to make the new lights working

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Okay, so I tested this and I have just one comment: I know you don't like the star effect, but to leave the nav lights and the beacon without the desaturated centre (which causes the star effect) makes them look so unrealistic in my opinion, they look just like a plain blob of colour, not like a light source to me. The strobes are looking really nice and the tail light as well.

I also found a little bug unrelated to the procedural lights but you might want to take a look at it in this same PR. Basically the landing and taxi lights look buggy from certain angles:

fgfs-screen-001

But if I turn the camera a tiny bit they look normal again:

fgfs-screen-002

**Comment by wlbragg** [comment]
>but to leave the nav lights and the beacon without the desaturated centre (which causes the star effect)

How much desaturation is needed before the star effect kicks in? Is there a middle ground that will stop the star effect but still allow enough desaturation to look good?

**Comment by gilbertohasnofb** [comment]
You know, in the end we are just trying to hack Thorsten's effect. Probably the best approach would be to ask him to reconsider it if we all feel strong about it...

**Comment by HHS81** [comment]
> but to leave the nav lights and the beacon without the desaturated centre (which causes the star effect) makes them look so unrealistic in my opinion,...

making the centre white makes the color disappear and you have a white star...., or a grey with a bit color an the outer part ....
But the color must be clear visible, otherwise no one recognize the flight direction of the aircraft.

Sorry but the lights simply not behaves like the Gimp SuperNovas. That's the best thing I can do - I don't like it:
fgfs-screen-001

fgfs-screen-002

I prefer to recognize the colors,

**Comment by gilbertohasnofb** [comment]
> But the color must be clear visible, otherwise no one recognize the flight direction of the aircraft.

Absolutely!

> Sorry but the lights simply not behaves like the Gimp SuperNovas. That's the best thing I can do - I don't like it

Look, I don't think the result is bad, I just think those textures were looking much better. But that said, there are other good things from a procedural approach.

Maybe someone wants to show those old lights we had to Thorsten and see if he would be up to try to "recreate" them procedurally.

**Comment by HHS81** [comment]
Just give him that: 
_Light effect decreases according to 1/r where r is the distance from star center._
_Radius
This is radius of the SuperNova center (1-100). When you increase the value, you increase the number of central white pixels according to r*r (1, 4, 9...)._
_Spikes
This is number of rays (1-1024). Each pixel in the nova center emit one pixel wide rays._

from: https://docs.gimp.org/en/plug-in-nova.html

**Comment by HHS81** [comment]
And ask him, which effects he does  likes on this pircture....:
fgfs-screen-007

**Comment by HHS81** [comment]
New try - please review

**Comment by HHS81** [comment]
@gilbertohasnofb  Ready for review!

**Comment by gilbertohasnofb** [comment]
Really nice work, Heiko! Looks much better IMO. At night-time, it looks fantastic!

**Comment by HHS81** [comment]
Thanks!

**Pull request merged**
