### PR TITLE
ALS landing and taxi lights

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
ALS landing and taxi lights

Closes https://github.com/HHS81/c182/issues/94

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@wlbragg do you know if the ALS landing lights are supposed to illuminate the propeller when the engine is off? Is there a way of making it illuminate only the ground?

**Comment by wlbragg** [comment]
Wow, I never noticed that one. I'll have to take a look at it and see what I think.

**Comment by gilbertohasnofb** [comment]
Yes, I tested it in the c172p and it also has some illumination in the propeller as well, but it's somehow less than the c182 (probably due to the viewing position and model size). If you think of something that could work, let me know.

**Comment by wlbragg** [comment]
I was able to get it off the prop using landing-light-offset3-deg set to 10.  landing-light-offset2-deg had an effect also. I don't recall of the top of my head which does what.

**Comment by gilbertohasnofb** [comment]
offset3 is the vertical offset, offset1 is the lateral offset. I found out that moving the lateral offset to -3 does the trick for the c182, so thanks for pointing it out!

**Comment by gilbertohasnofb** [comment]
@wlbragg in case you are wondering, this is what those properties do:

- `landing-light1-offset-deg` controls the landing light lateral offset
- `landing-light2-offset-deg` controls the taxi light lateral offset
- `landing-light3-offset-deg` controls both landing and taxi lights vertical offset

**Comment by gilbertohasnofb** [comment]
@HHS81 this is ready to be reviewed and possibly merged

**Pull request merged**
