### PR TITLE
Issue #106 and #112:

### PR DESCRIPTION
**Pull request by HHS81**
- Remove red and blue default livery
- add grey-black enhanced default livery
-remove VNE-caution decal as it only applies to turbo versions

### CODE REVIEW

**Comment by HHS81** [comment]
@gilbertohasnofb  ping

**Comment by gilbertohasnofb** [comment]
I will check this as soon as I can, in some few minutes!

**Comment by HHS81** [comment]
no hurry

**Comment by gilbertohasnofb** [comment]
Ok, testing this now

**Pull request merged**
