### PR TITLE
Issue #56: animation and texturing switches

### PR DESCRIPTION
**Pull request by HHS81**
textured switches
animated switches
corrected Master switches as they had been assigned to wrong functions
animated domelight buttons

Signed-off-by: HHS81 <Heiko.H.Schulz@gmx.net>

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Beautiful work, thanks a lot!

**Comment by gilbertohasnofb** [comment]
Hmm, there is a conflict with this branch. It seems that `dev/C182S.blend` has been modified on this branch, but it also has been modified on the previous PR about the flaps :cry: I am not very familiar on how to solve this type of conflicts, do you mind if I ask onox for some help?

**Comment by gilbertohasnofb** [comment]
And by the way, now that the radio and instrument illumination is working, how will we handle the panel illumination? Are we going to use a light map?

**Comment by HHS81** [comment]
> Hmm, there is a conflict with this branch. It seems that dev/C182S.blend has been modified on this branch, but it also has been modified on the previous PR about the flaps :cry: I am not very familiar on how to solve this type of conflicts, do you mind if I ask onox for some help?

I will look into, the `dev\c182s.blend` here in the branch should be the newer one. No idea why there is a conflict.

> And by the way, now that the radio and instrument illumination is working, how will we handle the panel illumination? Are we going to use a light map?

Yep, but before I want to alter the avionic illumination. They all behave completely different now, and all aircraft in fgfs and in X-Plane even handle it all in a different way. Some illuminate the face, some just the LED-numbers, some only the buttons....

After reading the POH, it seems to me the radio-light-button dims the LED-numbers and the button. 
The face are iluminated by the glareshield-light. 

I have written up what I plane in Issue #43

**Comment by gilbertohasnofb** [comment]
> I will look into, the dev\c182s.blend here in the branch should be the newer one. No idea why there is a conflict.

The conflict is because the last PR also had a modification to that blend file. So basically we had the blend file in the master at a stage A and two PR's with the blend file at stages B and C respectively. When the first PR was merged, the master's blend file went from A to B as instructed. But the second PR wants to change that blend file from A to C, and not from B to C. This is what is causing the conflict, it simply doesn't know what to do. Have you intended to modify the blend file in that flaps PR? If not, then probably you created the new branch while you already had modifications to the master, which may be the cause of the conflict. Makes sense?

And thanks for the info about the illumination!

**Comment by HHS81** [comment]
make sense, yes. Now, how to solve it?

**Comment by gilbertohasnofb** [comment]
The lazy way is to cancel this PR and delete this branch. Then create a new branch using the current master, and then reapply the modifications (basically recopy the files). Alternatively, there is some way of solving git conflicts via the terminal by choosing which file is to stay, but I am not familiar with that at all. If you want to do it the proper way, I'd have to ask help to onox or someone else from the c172p project.

**Comment by HHS81** [comment]
I use the lazy way, it is already very late here. Solving via terminal don't work, I tried.

**Comment by gilbertohasnofb** [comment]
Okay. So absolutely always before creating a new branch you should do a `git status` to confirm two things: 1) that you are in the master branch and 2) that it is clean. Also, always do a `git pull` before as well, to make sure that the master is the most current.

**Comment by HHS81** [comment]
next try - no error messages yet. Wait for your review

**Comment by gilbertohasnofb** [comment]
:+1: I will do it right now

**Pull request closed without merging**
