### PR TITLE
Issue #55: Static elements

### PR DESCRIPTION
**Pull request by HHS81**
Fix Issue #55 and Issue #82
updated 04/24/2016:

- use of geo.put_model for dynamic adding objects into scenery
-  each wheel chock clickable (with clickspots)
-  each clickable safety cones
- selectable wheel fairings
- changed color of tie-downs to yellow 
-  add walker
-  ladder (right or left), compatible with walker
-  external power unit
-  portable trailer fuel tank
-  implementation of aircraft tie-down
- gui update which reflects changes above
- changes to fdm with correct aileron deflections; forward slip and with that much more realistic crosswind behavior
- ASI reacts correct on failure/ pitot cover
- external power use of electrical system
- automatic disconnect when aircraft is moving

and maybe some minor things.....

### CODE REVIEW

**Comment by HHS81** [comment]
P.S.: changed key-binding for engine starter (now shift-s) due to walker.

**Comment by gilbertohasnofb** [comment]
I will review this now, but I strongly advise not to change the binding of the s key for the engine starter, that's the default for all aircraft and there will be tons of complaints like "why engine no work FG sux!" in the forum. Please reconsider it.

**Comment by HHS81** [comment]
> I will review this now, but I strongly advise not to change the binding of the s key for the engine starter, that's the default for all aircraft and there will be tons of complaints like "why engine no work FG sux!" in the forum. Please reconsider it.

Wait a moment pelase,....I think I know what happened.....

**Comment by gilbertohasnofb** [comment]
ok

**Comment by HHS81** [comment]
No, sorry.
There is strange bug with the walker. The s-key is only working in walker-views. It should be the way around.
I don't understand why. The author of the walker is already informed, I wait for answer. 
So the key-change is only temporarily, and mentioned in the help-file.

**Comment by HHS81** [comment]
We can change the key later, so if you want merge it though, I would be happy.

**Comment by gilbertohasnofb** [comment]
Okay, some comments:

- I still think the shift+S change is bad... we are kind of "breaking" something to revert it later
- `take ladder` toggle: is it really necessary? Why not only `place ladder on the <x> wing`?
- cones are not "clickable"
- pitot tube cover doesn't kill AIS
- tail tie-down: I'd rather have an shallower angle such as this:
fgfs-screen-001

What do you think?

**Comment by HHS81** [comment]
O.k., the electrical.nas is the cause for the issue. Why ever.... needs some time to solve.
ladder: I think about how to get this like proposed
cones: should they be? They are not part of the checklists.
pitot cover killing IAS: later together with pitot-icing
tail-tie-down: o.k.

So wait with the PR.

**Comment by gilbertohasnofb** [comment]
Ok Heiko, it's quite late here so I am going to sleep :zzz: I can merge this tomorrow when we are ready, ok?

> cones: should they be? They are not part of the checklists.

Yeah, I see your point, but I just don't see why not. Personally, I only use dialogs when I am forced to, I think they really break the immersion. Anyway, this is a minor detail.

Great work today, by the way. Cheers!

**Comment by HHS81** [comment]
s-key problem solved.

**Comment by HHS81** [comment]
ladder dialog and tiedown angles changed.
Everything else this or tomorrow evening

**Comment by gilbertohasnofb** [comment]
> s-key problem solved. 
> [...]
> ladder dialog and tiedown angles changed.
> Everything else this or tomorrow evening

Great, Heiko! Really appreciate the effort :+1: So when you are ready with the corrections, let me know so I can take another look at it and then merge it!

**Comment by HHS81** [comment]
@ onox: I guess it is an extended version of the nasal/math.nas in FGData?
Wouldn't be it better to get math-ext.nas into FGdata/nasal?

The tiedown is a great feature, but honestly said a bit pain to implement. Would be great if there would be a more simple method to include this (similar like the pushback truck) :smiley:

**Comment by HHS81** [comment]
> ladder dialog ....
FAILED!

the solution I choosed adds with every click on right or left ladder another instance model[0]; [1], [2];...
Without adding another 80lines of nasal-script I can't get it work.

The same would apply to the safety-cones and the chocks. 
Sorry, no idea how to do it better.

**Comment by gilbertohasnofb** [comment]
No problems then, Heiko. I think that clean GUI are very important, but if there is a practical reason or a limitation behind this decision, then we can live with it. Maybe one day you will think of an way of solving it :bulb:

**Comment by HHS81** [comment]
Maybe. maybe using geo.put-model() is indeed the better solution.....

**Comment by HHS81** [comment]
This is all I can think:
Enabling makes the ladders selectable
Unfortunately I can't make them seperatly working like that as clickable. 
That applies to chocks and pylons as well

So no real solution, beside geo.put-model() just for keeping the code small
fgfs-screen-006

**Comment by gilbertohasnofb** [comment]
Ok Heiko, I am not familiar at all with the code behind these. But I'd gladly test and merge this once you are happy with this PR, even if the solutions aren't perfect yet :smile:

**Comment by HHS81** [comment]
@gilbertohasnofb reade for review, please see entry of this PR for a complete list of changes

**Comment by gilbertohasnofb** [comment]
@HHS81 Ok Heiko! So I had a look at it, here are some thoughts:

- left and right tie-down can be removed by clicking on them, but cannot be added by clicking on the hotspot
- tail tie-down can't be added nor removed by click, only via menu
- chocks were a bit buggy sometimes. Adding them make the aircraft jump a bit in the air. Other times the wheels were completely not touching them (though this seems to be a bit more rare). Overall they work, but there is a lot of potential for bugs IMO.
- is it possible to disable wheel chocks and cones hotspots while on the air? It looks kind of ugly when pressing Ctrl+C now
- clicking on cone hotspots in the air toggle them between ON and OFF, which is strange
- automatically disconnect power unit if groundspeed > 0.0? Right now it looks funny if you forget the cable connected then start the plane

What do you think?

**Comment by HHS81** [comment]
@gilbertohasnofb 

> left and right tie-down can be removed by clicking on them, but cannot be added by clicking on the hotspot
tail tie-down can't be added nor removed by click, only via menu 

I improved the clickspots by simplifying it, so you should be able to add and remove them by clicking on it, unless the aircraft is moving

> chocks were a bit buggy sometimes. Adding them make the aircraft jump a bit in the air. Other times the wheels were completely not touching them (though this seems to be a bit more rare). Overall they work, but there is a lot of potential for bugs IMO.

I tried to improve it. Nethertheless it will only work o.k., when parking brake is set. That's how it will work in real life as well - the chocks are [only a safety addition to the parking brake](https://en.wikipedia.org/wiki/Wheel_chock). 
Also the jumping depends on the aircraft wheight. Less or even no jumping when aircraft is empty. JSBSim weirdness....

> is it possible to disable wheel chocks and cones hotspots while on the air? It looks kind of ugly when pressing Ctrl+C now
clicking on cone hotspots in the air toggle them between ON and OFF, which is strange

Done by disabling the clickspots when aircraft is moving

> automatically disconnect power unit if groundspeed > 0.0? Right now it looks funny if you forget the cable connected then start the plane

Good idea, done that way. 
But more realistic would be if distance >0.0. Will be a task for Milestone 2: I have the code somewhere for it since I used something similar for moving helipads, but can't find it here on my laptop. Not a showbreaker I think.

**Comment by gilbertohasnofb** [comment]
I will check this now, thanks for the quick fixes!

**Comment by gilbertohasnofb** [comment]
Heiko, everything is much better!:

- hot spots are all good now, but I think you had forgotten to add the speed condition to TiedownHotSpotLeft and TiedownHotSpotRight, and so it was possible to activate the tie-downs even if the aircraft was at a huge speed. I added these myself.
- The Fuel Tank Trailer label was spelt altogether in the menu (i.e. "Fueltanktrailer"), so I fixed that as well
- chocks seem much better now! I know that you are supposed to use them with parking brakes and engine off only, but I always try to "break" the plane while testing to find potential bugs. 

> But more realistic would be if distance >0.0. Will be a task for Milestone 2 [...] Not a showbreaker I think.

Sounds good, and definitely not a show breaker! :smile: I think we just need to solve the issues with the engine startup status and then we are ready for FGADdon!

**Comment by gilbertohasnofb** [comment]
So, just confirm if you are okay with my modifications in this branch, and we can merge this PR!

**Comment by HHS81** [comment]
> hot spots are all good now, but I think you had forgotten to add the speed condition to TiedownHotSpotLeft and TiedownHotSpotRight, and so it was possible to activate the tie-downs even if the aircraft was at a huge speed. I added these myself.

Oh, indeed. Thanks.

> The Fuel Tank Trailer label was spelt altogether in the menu (i.e. "Fueltanktrailer"), so I fixed that as well

yes, thanks. I accidently "germanized" it.

> chocks seem much better now! I know that you are supposed to use them with parking brakes and engine off only, but I always try to "break" the plane while testing to find potential bugs. 

Yes, I like this method to test. Meanwhile I had an idea, why it sometimes jump. It seems that the contact points are not matching correctly, due the gear compression in jsbsim. I have to think about a method how to let them match perfect. But this maybe for a later milestone, nowI think it is good enough. 

So I conform I'm o.k. with your modifications! :smile:

**Comment by gilbertohasnofb** [comment]
>  It seems that the contact points are not matching correctly, due the gear compression in jsbsim. I have to think about a method how to let them match perfect. But this maybe for a later milestone, nowI think it is good enough. 

Indeed when the bugs would appear the gear would change compression quite a lot up and down, so maybe we can have a look at it later. But let's merge this now! :smile:

**Comment by gilbertohasnofb** [comment]
:clap: :clap: :clap: very nice work, Heiko! I particularly love how the walker can climb the ladder, it's really amazing :smile:

**Comment by HHS81** [comment]
Yep, that was the reason why I wanted to use this method :smile: 
Thanks for merging, this was a long work, but worth it!

**Comment by gilbertohasnofb** [comment]
The result is really amazing, I am very happy with it!

**Pull request merged**
