### PR TITLE
Issue 111

### PR DESCRIPTION
**Pull request by HHS81**
I remade the knobs, animated them and change the alpha channel from the textures as it wasn't needed.

### CODE REVIEW

**Comment by HHS81** [comment]
@gilbertohasnofb  Ping

**Comment by gilbertohasnofb** [comment]
Checking it now!

**Comment by gilbertohasnofb** [comment]
Looks way better! I just have a tiny thing to ask, would you mind changing the UV map of the knobs a tiny bit? See the image below:

hi

On the left is how you map the main face of the knob, but I'd say that mapping it as the right side example would look better (that is, leaving a bit of the lighter grey around the main face). Makes sense?

**Comment by HHS81** [comment]
done

**Comment by gilbertohasnofb** [comment]
:+1: Perfect, thanks!

**Pull request merged**
