### PR TITLE
Electrical lightsystem

### PR DESCRIPTION
**Pull request by HHS81**
Using the work on the electrical and lighting system as test and practice for pull requests. (never tried before)
The whole systems are stil wip, and needs some work

### CODE REVIEW

**Comment by HHS81** [comment]
O.k, now that's easy

**Comment by onox** [comment]
> and practice for pull requests. (never tried before)

I have a couple of suggestions when using PR's on Github that you might want to use:

1. Use a short descriptive message in the summary (line 1) in your commit. The rule of thumb is to keep it less than 50 to 72 chars. Optionally you might want to add an extra multi-line message. Keep line 2 blank and add the multi-line message on line 3, 4, etc. Not all applications word-wrap automatically, so you should wrap it yourself. With `git commit -s`, git will add "Signed-off-by" on line 3 for you.

    [This](http://chris.beams.io/posts/git-commit/) is a nice blog post about how to write good git commit messages.

2. You might want to set a username. Your name is currently "unknown" instead of something like "HHS81". 

1. If the PR fixes a particular issue, then name the branch something like `bug-1`. If you then merge the branch you'll get a merge commit message like `Merge pull request #2 from HHS81/bug-1`. This way it is clear which bug got merged (1) while you can keep descriptive messages in your commit. So write something like `Add instrument X` instead of just `Fixes #1`. You can refer to the issue in the body (line 3, 4, etc.) If Github is/goes down, you can still understand what the commit does.

**Comment by gilbertohasnofb** [comment]
@onox got to love that xkcd comic on the top of the page :wink:

**Comment by HHS81** [comment]
@onox 
Great, many thanks, will follow it. 
:smiley:

**Pull request merged**
