### PR TITLE
Issue #46: AOMap

### PR DESCRIPTION
**Pull request by HHS81**
adding a gimp-post-processed shadowing layer of 70% Globa Illumination and 30% Ambient Occlusion made with Blender Cycles

### CODE REVIEW

**Comment by HHS81** [comment]
@gilbertohasnofb: 
Please review and merge.

Erik Hofman suggested in a private mail that we get the aircraft now into FGaddon, and let us fix the other issues later.
I agree, as the lightmaps needs some investigation from side to get the noise removed. This will need some time to figure out.

Do you agree?

**Comment by gilbertohasnofb** [comment]
It looks absolutely incredible! :astonished:

**Comment by gilbertohasnofb** [comment]
> Erik Hofman suggested in a private mail that we get the aircraft now into FGaddon, and let us fix the other issues later.

:+1: Absolutely! Let's make a release here in our repo, and then ask him to add it to FGAddon, what do you think?

**Comment by gilbertohasnofb** [comment]
@HHS81 hmm, I just spotted some small problems in the AOMap for the cockpit, see how these circuit breakers and switches are super dark while others aren't:

aomap

**Comment by HHS81** [comment]
Yeah, that was the reason I didn't made a pull request before. Forgot about that. Easy to fix, since I need only to exclude the switches, circuit breakers and other things from the layer in Gimp.

**Comment by gilbertohasnofb** [comment]
Ok! Once you create the new PR with the fix I will test it and merge it! Let me know if I can be of any help.

**Pull request merged**
