### PR TITLE
remove FuselageTexturing.png

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
Closes https://github.com/HHS81/c182/issues/84

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
Also, shouldn't we move `Models/flaps.png` to `Models/Instruments/flaps.png`? I think it makes more sense to have it there than in the main Models folder (looks cleaner)

**Comment by HHS81** [comment]
@gilbertohasnofb  we had this issue once. It isn't possible, as the texture must be there where the .ac-model lies.

**Comment by gilbertohasnofb** [comment]
Oh, I remember it now. Ok then, so then you can just merge this.

**Comment by HHS81** [comment]
done

**Comment by gilbertohasnofb** [comment]
Thanks!

**Pull request merged**
