### PR TITLE
-Fix Issue #61

### PR DESCRIPTION
**Pull request by HHS81**
also:
-improved tach
-improved hobbs meter

Signed-off-by: HHS81 <Heiko.H.Schulz@gmx.net>

### CODE REVIEW

**Comment by gilbertohasnofb** [comment]
@HHS81 I will check this now. By the way, it's always good to list all issues in the PR description, such as in:

Fixes #61 and #58

This not only keeps it organized, but (normally) closes the issues automatically once the PR is merged!

**Comment by gilbertohasnofb** [comment]
Also, the title "Fix Issue 61" isn't really good as it forces anyone interested in then chasing what is the issue 61 about. Something like "Fixing engine gauges" would be better. It is also good if you list everything that is improved, so in this case:

- fixing textures of FuelQTY, VacAmp and ManifoldGauge
- fixing position of the needles for FuelQTY, VacAmp and ManifoldGauge
- improvement to the tachometer and hobbs textures

Or something like that :smile:

**Comment by HHS81** [comment]
O.k. thanks!

**Comment by gilbertohasnofb** [comment]
No problems!

**Pull request merged**
