### PR TITLE
new splash9 showing night illumination on panel

### PR DESCRIPTION
**Pull request by gilbertohasnofb**
new splash9 showing night illumination on panel

### CODE REVIEW

**Comment by HHS81** [comment]
Wow :Wow:

**Comment by HHS81** [comment]
:open_mouth:

**Comment by gilbertohasnofb** [comment]
Yes, the new effects at night are stunning, Heiko, I think this is the best looking cockpit I've seen in FG! You did a fantastic job with it as always. Also the shadow effect are amazing, I love how the light in the panel turns its colour to bluish where there are no shadows:

**Comment by gilbertohasnofb** [comment]
@HHS81 I just realized this new splash is not showing the yokes. I retook the shot now:

fgfs-screen-002

What do you think? Should I exchange the splash9 for this shot here? I personally think so.

**Comment by gilbertohasnofb** [comment]
I opened a PR for this, see: https://github.com/HHS81/c182/pull/119

**Comment by HHS81** [comment]
An aircraft with controls  looks much better. :smile:

**Comment by gilbertohasnofb** [comment]
:+1:

**Pull request merged**
